Issue 36 (Work in progress)
intermine/intermine_boot pull request #39
Opened 2020-07-29 18:55 UTC by 22PoojaGaur

added github actions

Right now able to run `intermine_boot start local`. Todo: Add other mentioned test cases

2020-08-03 05:51 UTC, 22PoojaGaur commented
@uosl 
The actions run can be viewed in actions tab here [action run](https://github.com/22PoojaGaur/intermine_boot)

2020-08-05 08:17 UTC, leoank commented
Maybe the issue is with relative path. We can try using `Path(__file__).absolute()` instead of relative path to fix other tests.

2020-08-05 13:25 UTC, leoank requested changes
I am not sure that we need the contents in the action directory. Are you using it for something specific?

2020-08-05 13:25 UTC, leoank commented on .github/workflows/main.yml
> +            - uses: ./actions
Instead of this, it will be much simpler to install curl using a `run` command.
```
run: "apt install curl -y"
```

2020-08-05 14:04 UTC, leoank commented
I can confirm that using Path(__file__).absolute() solves the issue!

2020-08-06 06:21 UTC, leoank commented
Sorry! Replace run command with `run: sudo apt-get install curl -y`

2020-08-06 08:50 UTC, 22PoojaGaur commented
> I can confirm that using `Path(__file__).parent.parent.absolute()` solves the issue!

Hi @leoank how did you confirm?

I is working on local setup regardless of using `.absolute()` or not.
But it does not work on github actions run 

See the screenshot
![Screenshot from 2020-08-06 14-16-29](https://user-images.githubusercontent.com/43316760/89511688-df326980-d7ef-11ea-831b-a7bd564a7269.png)
link (https://github.com/22PoojaGaur/intermine_boot/runs/952970303?check_suite_focus=true)

2020-08-06 08:52 UTC, 22PoojaGaur commented
> Sorry! Replace run command with `run: sudo apt-get install curl`

Interesting. I thought the user would be root in docker container. Do you know why sudo is needed still it does not ask for a password while running the workflow?

2020-08-06 08:58 UTC, leoank commented
> I thought the user would be root in docker container

This is not always necessary. You can have users other than root. Github action containers are configured in this way and uses passwordless `sudo`.

2020-08-06 09:00 UTC, leoank commented
> Hi @leoank how did you confirm?

I am using https://github.com/nektos/act to run github actions locally.
after replacing `return Path(__file__).parent.parent / 'docker-intermine-gradle'` with `return Path(__file__).parent.parent.absolute() / 'docker-intermine-gradle'`, all tests passed.

2020-08-06 09:11 UTC, leoank commented
It is not ideal, but you can try printing the path that `_get_container_path()` is returning to debug the issue. Print the output of both the version of  `_get_container_path()`.

2020-08-06 09:13 UTC, leoank commented
Checked you build logs, curl is already installed inside the container. You can remove the run command to install curl.

2020-08-10 12:13 UTC, 22PoojaGaur commented
Actions ran at (actions)[https://github.com/22PoojaGaur/intermine_boot/runs/966487547?check_suite_focus=true]

2020-08-14 12:30 UTC, uosl commented
Looks like the tests run well and pass. Great job!

It seems we no longer use the `actions` dir. Can you delete this before we merge?

2020-08-14 13:01 UTC, 22PoojaGaur commented
> Looks like the tests run well and pass. Great job!
> 
> It seems we no longer use the `actions` dir. Can you delete this before we merge?

Right. done.

2020-08-14 13:24 UTC, heralden approved these changes
Thanks! :rocket:

2020-08-14 13:24 UTC, merged